# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c50013fe4611969502fe4de3da7f83ccd2d26b6ee7389338e20d2532661c1002b916d52701179816da8a942dfc008c13f8891e7678874c4322a1dae87ff717b

test:
  secret_key_base: 1ce8482aec75b0297df674f2f526d81c0f3a3a21ccd55caeb6ec589e5624803ec8928811590573e0ddcee62ea03e78c42c9bdf8ac427eee4bec8453c432fa0f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
